# Generated by Django 5.1.7 on 2025-04-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perosn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50, verbose_name=' First Name')),
                ('lname', models.CharField(max_length=255, verbose_name=' Last Name')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('gender', models.BooleanField(default=True, verbose_name='Gender')),
                ('phone', models.CharField(max_length=15, verbose_name=' Phone Number')),
            ],
        ),
    ]
