# Generated by Django 5.1.7 on 2025-04-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perosn',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='perosn',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perosn',
            name='gender',
            field=models.BooleanField(default=True, verbose_name='Gender , True=MAN'),
        ),
        migrations.AlterField(
            model_name='perosn',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name=' Phone Number'),
        ),
    ]
