# Generated by Django 5.1.7 on 2025-04-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonApp', '0002_alter_perosn_options_perosn_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perosn',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
