# Generated by Django 5.1.7 on 2025-04-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_post_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num',
        ),
    ]
