# Generated by Django 5.1.7 on 2025-04-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_post_mail_remove_post_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(verbose_name='Post Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text_1',
            field=models.CharField(max_length=255, verbose_name='Text Number 1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text_2',
            field=models.CharField(max_length=255, verbose_name='Text Number 2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_des',
            field=models.CharField(max_length=255, verbose_name='Post Title'),
        ),
    ]
