# Generated by Django 5.1.7 on 2025-04-25 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=250)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IOMoney',
            fields=[
                ('addeddate', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.FloatField(default=0)),
                ('desc', models.CharField(max_length=500)),
                ('iodate', models.DateField()),
                ('familymember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.family')),
            ],
        ),
    ]
