# Generated by Django 5.1.7 on 2025-04-14 17:00

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=250, verbose_name='Full Name')),
                ('phone1', models.CharField(max_length=15, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone 2')),
                ('clientType', models.BooleanField(default=False, verbose_name='Owner=True, Seeker=False')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', django_jalali.db.models.jDateField()),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('rooms', models.IntegerField(default=1)),
                ('size', models.IntegerField(default=1)),
                ('buildingyear', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assets.client')),
            ],
        ),
    ]
